### ISSUE TITLE
How well can Unreal CV work with different UE4 environments? 

### ISSUE THREAD

**Issue by olivia-skydio** [unrealcv/unrealcv#113]
- Operating System: Ubuntu 16.04
- UE4 Version: 4.16
- UnrealCV Version: 3.10
- Client (python2, 3 or matlab):python2
- Problem Description:

How robust should unrealCV work with new/different environments that can be found on the UE4 marketplace? I'm trying to use to a Redwood forest scene that I've previously used (in UE4 Version 4.17), and added the UnrealCV plugin and unreal engine editor is really buggy/slow/lagging when starting up/loading the editor/building the environment and not all the lighting is able to load (not sure if this is a UE4 version issue or unreal version issue). Could this just be the content for the environment I'm working with is too large (even though it works fine on UE4 4.17 without the plugin)? Should it work well with other large content? Or should I stick to the available environments found in the model zoo for best use. Also, the unreal commands work fine, its just getting it all set up that is slow/buggy. 

Thanks so much!

**Comment by qiuwch** [comment]
Hi, @olivia-skydio 

Thanks for this issue. You brought up a very important thing I am working on.

The performance issue is mainly because the sensors created by unrealcv are capturing data everytime (which is unnecessary). If the rendering cost is low, the impact is not significant, but if it is a very complex scene, the performance suffers.

You can check the performance cost using a console command `ProfileGPU`, which described here, https://docs.unrealengine.com/latest/INT/Engine/Performance/GPU/.

The branch I am currently working on has some significant performance improvement, but I am not sure how much it is for the environment you are working on. I purchased the Redwood today and will get some numbers tomorrow.

**Comment by olivia-skydio** [comment]
Thanks for getting back to me, I'll check it out and would love to stay up to date on how it goes @qiuwch !
