### ISSUE TITLE
Problem with UnrealCV plugin for Unreal Engine 4.12

### ISSUE THREAD

**Issue by sudk1896** [unrealcv/unrealcv#41]
Hey, I'm trying to compile a game binary using unrealcv plugin but am unable to do so.
```
MainFrameActions: Packaging (Linux): mono: LogCompile: /home/sudarshan/UnrealEngine/Engine/Plugins/unrealcv/Source/UnrealCV/Public/TcpServer.h(50): Error: Property is exposed to the editor or blueprints but has no Category specified.
```
This is the error I'm getting.
The complete error log is  [here](http://pastebin.com/sJVmcNnk)

**Comment by qiuwch** [comment]
Hi, @sudk1896 
Please see #13.
This is fixed in the develop branch, but I am still doing testing and did not merge it to the master branch yet.
I am writing the docs [here](https://qiuwch.gitbooks.io/unrealcv/content/). It is still in a draft status, so I did not publish it anywhere.
I am very busy working integrating protobuf with unrealcv and sorry for the late reply.

**Comment by sudk1896** [comment]
@qiuwch : Thanks. Will do.
