### ISSUE TITLE
Get various images directly as numpy arrays or similar 

### ISSUE THREAD

**Issue by debadeepta** [unrealcv/unrealcv#60]
Hi,

Is it possible to get the depth image (and other images) directly in python as numpy arrays instead of saving to a file and then reading them back to Python? I could not figure out how to do so from the commands list or examples.

Thanks in advance!

**Comment by qiuwch** [comment]
Load png as a numpy array is possible in the develop branch. See here: http://docs.unrealcv.org/en/develop/CHANGELOG.html. This is very new and is not merged to master branch yet.

A generic implementation of returning any matrix as numpy array is what I am working on right now, using this library. https://github.com/rogersce/cnpy. After finishing this, I will merge the update to master.

**Comment by debadeepta** [comment]
Both of the above methods still seem to be saving to file (png or npy/npz) and then reading them back, right? What I meant was bypassing the disk completely and directly getting the image/depth image buffer from the game side and surfacing it in Python as numpy arrays.

My application is reinforcement learning and I don't want to save any images to disk at all during training time. The images and depth images are to be consumed by the agent under training and thrown away. If I go through disk then training will be really slow and also the disk will start filling up with millions of images.

**Comment by qiuwch** [comment]
For lit, depth, normal, the data won't be saved to the disk. The raw data will be encoded in the memory and be sent through socket directly. For object_mask, due to the way it is generated right now (vertex paint + screenshot). I can not bypass the file save step.

The code I mentioned is in here
https://github.com/unrealcv/unrealcv/blob/develop/Source/UnrealCV/Private/Commands/CameraHandler.cpp#L404
https://github.com/unrealcv/unrealcv/blob/develop/Source/UnrealCV/Private/GTCaptureComponent.cpp#L234

The npy code is still very experimental and not in github. AirSim can take these chunks of code if they are useful to you.  : )

**Comment by debadeepta** [comment]
I don't need the object mask right now, so this feature is perfect for me. What are the commands to get this data via the UnrealCV API and which branch should I use to get this feature?

UnrealCV is perfect for some of our RL projects which do not need robot dynamics (yet) or are only vision based. 

Regarding AirSim: Will point Shital Shah and Chris Lovett to this thread.

PS: UnrealCV is really impressive work!

**Comment by qiuwch** [comment]
Thanks very much for the kind words. 

Please try the develop branch.
The documentation for develop branch is http://docs.unrealcv.org/en/develop/
`vget /camera/0/lit png` is working, I am working on `vget /camera/0/depth npy` which can return depth as a numpy array (because png has range limit 0-255). 

You need to compile the code http://docs.unrealcv.org/en/develop/plugin/install.html#compile-from-source-code, which should be able to support both linux and windows.

My friend is working on an unreal-based OpenAI gym environment. If you are interested in, I can connect you two, maybe can save you some efforts.

**Comment by debadeepta** [comment]
I will compile from source then. Please let me know when you get the depth working as well. That is necessary for me. 

Is your friend's project this one: https://github.com/zfw1226/gym-unrealcv
If so I wonder how is he solving the disk bypass issue for doing RL with OpenAI gym.

Many thanks again! I will close this thread now and await the depth update in the meantime.

**Comment by qiuwch** [comment]
It has been added in v0.3.9, please see here http://docs.unrealcv.org/en/develop/tutorials/generate_images_tutorial.html. I did not have time to benchmark the speed yet, but I think the bottleneck is in reading buffer from UE4, and skipping the file IO does not provide a lot gain.

**Comment by mikeroberts3000** [comment]
I very roughly benchmarked the old way and the new way of obtaining color and depth images. I noticed a consistent 3x speedup using the new interface on a Windows desktop machine. Total roundtrip time using the old interface is roughly 1.0 seconds per image, and using the new interface is roughly 0.3 seconds per image. So not a life-changing performance difference, but well worth the one-liner code change (one-liner change to my code that is; implementing this new functionality in UnrealCV was certainly much more effort; thanks @qiuwch 😄).

**Comment by qiuwch** [comment]
@mikeroberts3000 

Thanks very much for doing something I want to do for quite a while  👍.
I should include a benchmark script in the project to track the speed improvement overtime.

I am very behind of optimizing the speed of the low level. I had some conversations with Shital but did not have enough time to push that forward yet.

**Comment by edgarriba** [comment]
hi! why 'lit' mode returns a 4 channel matrix ?

**Comment by mkisantal** [comment]
As I remember images are returned in RGBA color space, so the fourth channel corresponds to alpha (opacity).

**Comment by edgarriba** [comment]
cool. Thanks !
