### ISSUE TITLE
The RealisticRendering app for Mac is unavailable

### ISSUE THREAD

**Issue by xtrawurst** [unrealcv/unrealcv#7]
I get a message

Not Found
The requested URL /~qiuwch/unrealcv/binaries//RealisticRendering-mac.zip was not found on this server.

in the browser window.

**Comment by qiuwch** [comment]
Sorry for the inconvenience. The reason is I don't have enough time to build the Mac version yet. Manually compiling binaries for three platforms takes time, especially the code is frequently updated.

I will put a Mac version online tonight. I am also working on setting up a Jenkins CI to solve this issue. The Travis config of this repo just does some very simple testing. Has anyone a good recommendation for CI option?

**Comment by jacobsn** [comment]
It is online now and working on my mac laptop: http://www.cs.jhu.edu/~qiuwch/unrealcv/binaries/RealisticRendering-Mac-65d6144-c25660b.zip

**Comment by qiuwch** [comment]
@jacobsn Thanks for updating here. I just compiled it and did not have time to fully test it. Let me know if you find any issue.

I will update the website later.
