### ISSUE TITLE
How are the surface normals encoded in the png images?

### ISSUE THREAD

**Issue by Mayankm96** [unrealcv/unrealcv#77]
I am trying to use UnrealCV for my project in which I need to create a mask for all the points facing upwards from the ground. 

For this, I intend to capture the surface normals view that we get and then normalize the values so that from 0 to 255 it scales to 0 to 1. After that, I take a dot product of the normals with a matrix having element (0,0,1) and use that to take the angle between the normal and the direction perpendicular to the ground. 

However, the above procedure is not working for me and I believe it is because [x y z] is not the same as the [r g b] values. I would like to know the appropriate modifications I should do.

Thank you!

**Comment by qiuwch** [comment]
![image](https://user-images.githubusercontent.com/1688418/28297244-de7410f4-6b3a-11e7-89d8-d0025a93fec6.png)

This is the linear mapping used in the surface normal generation, which is taken from UE4. Probably you need to inverse this operation. I did not use surface normal in my research, so not quite sure about whether this is what you want.

**Comment by mikeroberts3000** [comment]
@qiuwch is correct. You have to undo the function in the screenshot above to recover the world-space normal.

**Comment by qiuwch** [comment]
@mikeroberts3000 Probably I should take out the mapping, no one doing computer vision cares about this mapping which makes visualization better. But this will be a breaking change, making it incompatible with previous code.

**Comment by Mayankm96** [comment]
@qiuwch I apologize for replying a bit late. I am not well experienced with UE4Editor, but does the `SceneTexture:WorldNormal` color node gives values in float32 which is then transformed according to following relation: `output = 0.5*input + 0.5`, and mapped to uint8 by a multiplication with 255?

Also I found the RGBMatBall which kinda seems to show well how the axis are oriented.. I think. 
![rgbmatball](https://user-images.githubusercontent.com/12863862/28495146-275c032c-6f45-11e7-9ae4-06f7790113db.png)

**Comment by mikeroberts3000** [comment]
@Mayankm96 that is correct. You can verify the correctness of your interpretation by turning on the debug camera (i.e., hit ` while in an active Unreal game window to bring up the console and type ToggleDebugCamera). This will print the coordinates of the camera, so you can get a sense of the Unreal coordinate system. Then, when you inspect the normal images you get from UnrealCV, you'll see that the normals of visible surfaces match the intuition you got from moving the debug camera around (i.e., moving the camera away from a flat surface will move the camera in the direction of that surface's normal).

**Comment by Mayankm96** [comment]
Yeah it all makes sense now. Thanks for your help! :)

**Comment by xiaoxiangyeyuwangye** [comment]
@qiuwch Thanks for your awesome work. 
If I understand correctly, the out normal vector is under world coordinate.
If I want to get normal vector under camera coordinate do your have any suggestion about how to realize it?
Thanks for any suggestion.

**Comment by mikeroberts3000** [comment]
@xiaoxiangyeyuwangye It has been a while since I've used UnrealCV, so the exact syntax I'm suggesting might have changed slightly. If anyone knows of a more direct way of doing this in 2019, please correct me. But in 2017, the easiest way of converting between world space and camera space was as follows.

First, you can use UnrealCV to obtain the camera orientation as a triple of Euler angles.

```
pitch, yaw, roll = unrealcv.client.request("vget /camera/0/rotation")
```

Second, you can construct the matrix that maps points from world space to camera space. For this purpose, I have always liked `transformations.py` by Christoph Gohlke, which is useful for converting between different attitude representations.

```
import transformations
R_world_from_cam = matrix(transformations.euler_matrix(pitch, yaw, roll,"ryxz")[0:3,0:3]
R_cam_from_world = R_world_from_cam.T
```

(Note that a triple of Euler angles can be interpreted 24 different ways. This is one of the reasons why people dislike working with Euler angles. The string `"ryxz"` in the code snippet above specifies the particular Euler angle convention used by the `transformations` library. This choice was correct for me, based on the surrounding conventions in the rest of my code, but it may not be correct for you. See the inline documentation in `transformations.py` for more details.)

Now you can map world space vectors into camera space with matrix multiplication.

```
v_cam = R_cam_from_world*v_world
```

Anyway, I hope this explanation helps you to get your normals (or any other vectors) into camera space 😄
